// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sokyouilebtynwwayawn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNva3lvdWlsZWJ0eW53d2F5YXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODMyMzQsImV4cCI6MjA2Njc1OTIzNH0.Q8xRtAi34Z8cDuSFhIT-Aaj84fTvB6y1EARA3Lyb9XA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);